KS-4-3 Выполнил задание 3 урок 4
alexglazyrin/kotlinSprint pull request #20
Opened 2024-08-12 13:25 UTC by alexglazyrin

2024-08-13 14:39 UTC, ievetrovdev requested changes

2024-08-13 14:39 UTC, ievetrovdev commented on src/main/kotlin/lesson4/lesson4_task3.kt
> +                            && isOpen == GOOD_IS_OPEN
хоть и согласно https://kotlinlang.org/docs/coding-conventions.html конвенции нет строгих правил переноса длинных условия, на моей практике я везде встречал так: сначала на строке остается && / || , а затем строка переносится

2024-08-13 14:39 UTC, ievetrovdev commented on src/main/kotlin/lesson4/lesson4_task3.kt
> +                        true
при перечислении параметров лучше в каждой строке оставлять запятую, будет удобнее при расширении количества параметров

2024-08-13 14:39 UTC, ievetrovdev commented on src/main/kotlin/lesson4/lesson4_task3.kt
> +                    isSunny == GOOD_IS_SUNNY
для удобного чтения лучше выделить результат выражения в отдельную переменную

2024-08-14 07:33 UTC, alexglazyrin commented on src/main/kotlin/lesson4/lesson4_task3.kt
> +                    isSunny == GOOD_IS_SUNNY
принято

2024-08-14 07:34 UTC, alexglazyrin commented on src/main/kotlin/lesson4/lesson4_task3.kt
> +                            && isOpen == GOOD_IS_OPEN
принято

2024-08-14 07:34 UTC, alexglazyrin commented on src/main/kotlin/lesson4/lesson4_task3.kt
> +                        true
принято

2024-08-14 14:12 UTC, ievetrovdev approved these changes

2024-08-14 15:13 UTC, merged