KS-4-4 Выполнил задание 4 урок 4
alexglazyrin/kotlinSprint pull request #21
Opened 2024-08-13 05:42 UTC by alexglazyrin

2024-08-13 14:35 UTC, ievetrovdev requested changes

2024-08-13 14:35 UTC, ievetrovdev commented on src/main/kotlin/lesson4/lesson4_task4.kt
> +    if (dayCount % 2 == 0) {
Так как частей тела может быть больше, я бы не ограничивался ими в переменных.
Достаточно одной переменной для нахождения четности числа и далее ее применять. типа того isEven / !isEven

2024-08-14 07:48 UTC, alexglazyrin commented on src/main/kotlin/lesson4/lesson4_task4.kt
> +    if (dayCount % 2 == 0) {
Если я правильно понял посыл, то:

2024-08-14 14:13 UTC, ievetrovdev approved these changes
Да, правильно

2024-08-14 15:13 UTC, merged