KS-5-1 Выполнил задание 1 урок 5
alexglazyrin/kotlinSprint pull request #23
Opened 2024-08-14 08:52 UTC by alexglazyrin

2024-08-14 19:35 UTC, ievetrovdev requested changes

2024-08-14 19:35 UTC, ievetrovdev commented on src/main/kotlin/lesson5/lesson5_task1.kt
> +    val firstNumber = Random.nextInt(0, 100)
Как правило для таких функций есть более свежие, более удобные и лучше читаемые альтернативы в виде экстеншн функций. Более современными инструментами в принципе нормально пользоваться) Здесь я бы использовал экстеншн получения рандомного числа из диапазона:` (1..10).random()`

2024-08-14 19:35 UTC, ievetrovdev commented on src/main/kotlin/lesson5/lesson5_task1.kt
> +    val userAnswer = readLine()!!.toInt()
Использование оператора `!!` подразумевает, что ты уверен в том, что значение не может быть `null`. Однако, если это не так, то приложение "упадет" с ошибкой. Поэтому этот оператор считается опасным и не рекомендуется использовать. Только в крайних случаях. Это противоречит основной идее безопасности типов в Kotlin, поэтому лучше использовать альтернативные способы обработки нулабельных значений. Такие как оператор безопасного вызова `?.`, элвис-оператор `?:` или оператор `let`.

2024-08-14 19:37 UTC, alexglazyrin commented on src/main/kotlin/lesson5/lesson5_task1.kt
> +    val firstNumber = Random.nextInt(0, 100)
Я не знал)))

2024-08-14 19:38 UTC, alexglazyrin commented on src/main/kotlin/lesson5/lesson5_task1.kt
> +    val userAnswer = readLine()!!.toInt()
Иваааааан, ты в видео говорил, что мы потом узнаем про два восклицательных))))
Я немного пишу на котлину на работе, но меня пока не раскрыли....

2024-08-15 07:11 UTC, ievetrovdev approved these changes
Всё хорошо, двигаемся дальше. 
На счёт `readLine()`. Пока я рекомендую использовать более свежую функцию readln(). Метод под капотом обрабатывает нулябельность и все кастует в строку (в том числе null становится строкой “null”)

2024-08-15 07:26 UTC, merged