KS-1-4
alexglazyrin/kotlinSprint pull request #4
Opened 2024-08-07 12:43 UTC by alexglazyrin

2024-08-07 14:44 UTC, ievetrovdev requested changes
Не все типы данных проставлены

2024-08-07 14:44 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task4.kt
> +    val partOfDay = 0.075F
Тут ты при помощи F числу 2.0547945205479453E-4 обрезаешь часть знаков после запятой до 2.0547945E-4. Если есть задача где это критично, можно получить ошибку в расчетах.

2024-08-07 14:44 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task4.kt
> +    val partOfYear = 2.0547945205479453E-4
А тут у нас какой будет тип данных?

2024-08-07 14:54 UTC, alexglazyrin commented on src/main/kotlin/lesson1/lesson1_task4.kt
> +    val partOfYear = 2.0547945205479453E-4
Насколько мне известно (могу ошибатьс), по умолчанию Int присваивается к целочисленному....

2024-08-07 14:57 UTC, alexglazyrin commented on src/main/kotlin/lesson1/lesson1_task4.kt
> +    val partOfDay = 0.075F
Не очень понял.... float у меня к 0.075, а дабл у меня в консоли выдает без потери точности:
40868600000
27
0.075
6480
2.0547945205479453E-4
327000

2024-08-08 07:14 UTC, ievetrovdev requested changes

2024-08-08 07:14 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task4.kt
> +    val partOfDay = 0.075F
Тут F , применено верно, но тип у переменной обязательно надо проставить

2024-08-08 07:14 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task4.kt
>      val partOfYear = 2.0547945205479453E-4
Прошу прощения, засмотрелся. Комментарий про F и то что он обрезает часть числа,  касался переменной **partOfYear**. К таким числам лучше не применять, во избежание неточных вычислений. Что касаемо типа данных у переменной **partOfYear**, если видим точку - это автоматически **Double** или **Float**. но для больших чисел коммент выше актуален. поэтому здесь верный ответ будет **Double**

2024-08-08 10:06 UTC, ievetrovdev approved these changes
Отлично, двигаемся дальше.

2024-08-08 10:20 UTC, merged